from __future__ import annotations

import argparse
from datetime import date, datetime
from pathlib import Path

from data_pipeline.jobs.check_trade_day import _load_trade_dates_from_akshare


def _parse_date(value: str) -> date:
    return datetime.strptime(value, "%Y-%m-%d").date()


def _default_start() -> date:
    today = date.today()
    return date(today.year, 1, 1)


def _default_end() -> date:
    today = date.today()
    return date(today.year + 1, 12, 31)


def build_trade_calendar_sql(trade_dates: list[str], source: str = "akshare") -> str:
    if not trade_dates:
        raise RuntimeError("No trade dates found for the requested range.")

    safe_source = source.replace("'", "''")
    values = ",\n".join(f"  ('{trade_date}', '{safe_source}')" for trade_date in trade_dates)
    return (
        "-- Generated by data_pipeline.jobs.export_trade_calendar_sql\n"
        "-- Paste into Supabase SQL Editor after running supabase/schema.sql.\n"
        "insert into public.a_share_trade_calendar (trade_date, source)\n"
        "values\n"
        f"{values}\n"
        "on conflict (trade_date) do update\n"
        "  set source = excluded.source;\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Export real A-share trading dates as Supabase SQL.")
    parser.add_argument("--start", default=_default_start().isoformat(), help="Start date, YYYY-MM-DD.")
    parser.add_argument("--end", default=_default_end().isoformat(), help="End date, YYYY-MM-DD.")
    parser.add_argument(
        "--output",
        default="supabase/a_share_trade_calendar_seed.sql",
        help="Output SQL file path.",
    )
    parser.add_argument("--stdout", action="store_true", help="Print SQL instead of writing a file.")
    args = parser.parse_args()

    start = _parse_date(args.start)
    end = _parse_date(args.end)
    if start > end:
        raise ValueError("--start must be on or before --end")

    all_dates = sorted(_load_trade_dates_from_akshare())
    selected = [trade_date for trade_date in all_dates if start <= _parse_date(trade_date) <= end]
    sql = build_trade_calendar_sql(selected)

    if args.stdout:
        print(sql)
        return

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(sql, encoding="utf-8")
    print(f"Wrote {len(selected)} trade dates to {output_path}")


if __name__ == "__main__":
    main()
